Implements MemoryLoader concept
xmos/tensorflow pull request #21
Opened 2021-03-30 18:14 UTC by keithm-xmos

This PR implement the concept of the MemoryLoader.

The two "reference" XCoreInterpreter class constructor API have not been modified.  The reference implementation will now construct the reference MemoryLoader class (allocated in the arena).  The reference MemoryLoader object is useful for models stored in any external memory segment (SwMem or ExtMem), however, it is inefficient on models stored in flash SwMem.  

A MemoryLoader input argument has been added to the non-reference XCoreInterpreter class constructor. It is anticipated that an application developer would provide a custom MemoryLoader and override the Load() method.

2021-03-30 19:58 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_interpreter.cc
> +  SetMemoryLoader(std::addressof(loader));
Unless `MemoryLoader` is expected to overload the `&` operator, we should stick to
```suggestion
  SetMemoryLoader(&loader);
```

2021-03-30 19:58 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_interpreter.cc
> +  MemoryLoader* loader = new (loader_buf) MemoryLoader();
If `loader_buf` is not used for anything else, the cast is not necessary:
```suggestion
  auto* loader_buf = allocator->AllocatePersistentBuffer(sizeof(MemoryLoader));
  auto* loader = new (loader_buf) MemoryLoader();
```

2021-03-30 19:58 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_memory_loader.h
> +  virtual void Load(void *dest, const void *src, size_t size) {
Should the arguments be `Load(void *&dest, const void *src, size_t size)` to allow implementations to perform the short circuit that `FetchBuffer` does for SRAM addresses? If yes, it should also return `size_t` similarly to `FetchBuffer`.

(Also, the implementation should go into the `.cc`)

2021-03-30 21:23 UTC, keithm-xmos commented
Some feedback has been integrated.  Still not ready to merge.  

Still looking into how to leverage static polymorphism is a clean way.

2021-04-05 14:33 UTC, lkindrat-xmos requested changes
Interface looks good! Some small fixes are needed, mostly in the documentation. Please make sure everything is formatted.

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_memory_loader.h
> +   * one may need to syncronize access to the memory.
This would be better placed in the interface.

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_memory_loader.cc
> +  // TODO: consider using different implementations for flash/DDR
This comment can now be removed

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_utils.h
>  size_t FetchBuffer(T **dest, T const *src, size_t size) {
```suggestion
inline size_t FetchBuffer(T **dest, T const *src, size_t size) {
```

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_utils.h
> +  return loader->Load((void **)dest, (void *)src, size);
```suggestion
  auto *loader = tflite::micro::xcore::GetMemoryLoader();
  return loader->Load((void **)dest, (void *)src, size);
```

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_interpreter.cc
> +  //   The MemoryLoader is dynamically allocated from the arena
```suggestion
```

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_interpreter.cc
> +  // Initialize the profiler (if provided)
```suggestion
```

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_dispatcher.h
> +//       by STACKWORDS_ALIGNMENT_ADJUSTMENT.  This is because the
```suggestion
//       size up by STACKWORDS_ALIGNMENT_ADJUSTMENT.  This is because the
```

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_interpreter.h
> +   * This constructor is provide for an application that wishes to provide
```suggestion
   * This constructor is for applications that provide
```

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_interpreter.h
> +   * object. If ommtted or null, no profiling will be performed which reduces
```suggestion
   * object. If omitted or null, no profiling will be performed which reduces
```

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_interpreter.h
> +   * If ommtted or null, no profiling will be performed which reduces the code
```suggestion
   * If omitted or null, no profiling will be performed which reduces the code
```

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_interpreter.h
> +   * If ommtted or null, no profiling will be performed which reduces the code
```suggestion
   * If omitted or null, no profiling will be performed which reduces the code
```

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_interpreter.h
> +   * implementation is does not so is more memory friendly.
```suggestion
   * This implementation hides a method in the base class that performs
   * a persistent arena allocation for every call. Instead, this implementation
   * just returns a pointer to the underlying TfLiteTensor object, so it does
   * not explode the arena when the method is called repeatedly.
```

2021-04-05 14:33 UTC, lkindrat-xmos commented on tensorflow/lite/micro/kernels/xcore/xcore_memory_loader.h
> +   * Load memory from an external memory segment.
```suggestion
   * Load memory from a potentially external memory segment.
```

2021-04-05 18:39 UTC, merged